version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'typescript'
        versions: ['5.9.x', '6.x', '7.x']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
