name: publish-src-to-github-pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Use Node V22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ghpages

      - name: Publish current web page to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          # You can use whatever directory your project uses, for example "wwwroot".
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically by your static website builder.
          source-directory: ghpages

          # Optional. Default value "gh_pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will OVERWRITE this branch.
          target-branch: gh_pages
